export const ChatData = [
  {
    id: 1,
    Name: 'John Smigla',
    ProfileImg: 'www.example.com',
    LastSeen: '35 min ago',
    UnreadMsgs: '5',
  },
  {
    id: 2,
    Name: 'Alice Johnson',
    ProfileImg: 'www.example.com',
    LastSeen: '10 min ago',
    UnreadMsgs: '2',
  },
  {
    id: 3,
    Name: 'David Miller',
    ProfileImg: 'www.example.com',
    LastSeen: '45 min ago',
    UnreadMsgs: '1',
  },
  {
    id: 4,
    Name: 'Emily Williams',
    ProfileImg: 'www.example.com',
    LastSeen: '20 min ago',
    UnreadMsgs: '3',
  },
  {
    id: 5,
    Name: 'Michael Brown',
    ProfileImg: 'www.example.com',
    LastSeen: '15 min ago',
    UnreadMsgs: '1',
  },
  {
    id: 6,
    Name: 'Sophia Davis',
    ProfileImg: 'www.example.com',
    LastSeen: '5 min ago',
    UnreadMsgs: '4',
  },
  {
    id: 7,
    Name: 'Daniel Wilson',
    ProfileImg: 'www.example.com',
    LastSeen: '50 min ago',
    UnreadMsgs: '1',
  },
  {
    id: 8,
    Name: 'Olivia Martinez',
    ProfileImg: 'www.example.com',
    LastSeen: '30 min ago',
    UnreadMsgs: '2',
  },
  {
    id: 9,
    Name: 'William Anderson',
    ProfileImg: 'www.example.com',
    LastSeen: '25 min ago',
    UnreadMsgs: '1',
  },
  {
    id: 10,
    Name: 'Emma Garcia',
    ProfileImg: 'www.example.com',
    LastSeen: '40 min ago',
    UnreadMsgs: '1',
  },
]
